spring:
  application:
    name: co2diet-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/co2diet
    username: co2diet
    password: co2diet
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    com.reduceco2now: DEBUG